pmtiles:
  sources:
    alaska: /tiles/alaska.pmtiles
    atlantic: /tiles/conus_atlantic_gulf_tiles.pmtiles
    pacific: /tiles/conus_pacific_tiles.pmtiles
    great_lakes: /tiles/great_lakes_tiles.pmtiles
    hawaii: /tiles/hawaii_tiles.pmtiles
    pr_usvi: /tiles/pr_usvi_tiles.pmtiles
