version: "3.8"

services:
  jupyterlab:
    image: jupyter/base-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ~/efs/jupyterlab-compose:/home/jovyan/work
    environment:
            JUPYTER_ENABLE_LAB: "yes"
            NB_UID: "1000"
            NB_GID : "100"
            AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
            AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
            AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
    command: > 
            bash -c "pip install boto3 && chown -R 1000:100 /home/jovyan/work && start-notebook.sh --NotebookApp.token=''"
